steps:
  - task: NodeTool@0
    displayName: "Use Node 10.x"
    inputs:
      versionSpec: 10.x
  - task: connect-agent@2
    inputs:
      hostedAgentService: "90469226-70c7-4fd9-acf1-a6f54739e00a"

  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: "Replace tokens"
    inputs:
      rootDirectory: "$(System.DefaultWorkingDirectory)"
      targetFiles: |
        tasks/daticaliSeriesV1/task.json
        vss-extension.json
      verbosity: detailed
      encoding: "utf-8"
      tokenPrefix: "#{"
      tokenSuffix: "}#"

  - task: SonarSource.sonarqube.15B84CA1-B62F-4A2A-A403-89B77A063157.SonarQubePrepare@4
    displayName: "Prepare analysis on SonarQube"
    inputs:
      SonarQube: SonarWindows
      scannerMode: CLI
      configMode: manual
      cliProjectKey: "$(Build.Repository.Name)"
      cliProjectName: "$(Build.Repository.Name)"
      cliProjectVersion: "$(Build.BuildNumber)"
      cliSources: "$(System.DefaultWorkingDirectory)"
      extraProperties: |
        sonar.projectBaseDir=$(System.DefaultWorkingDirectory)
        sonar.exclusions=node_modules/**,coverage/**,examples/**,docs/**,reports/**,**/node_modules/**,**/*.js
        sonar.sources=tasks/daticaliSeriesV1
        sonar.sourceEncoding=UTF-8
        sonar.tests=tasks/daticaliSeriesV1/__tests__
        sonar.test.inclusions=**/*Test.ts,**/*test.ts,**/*spec.ts
        sonar.testExecutionReportPaths=coverage/sonar-report.xml
        sonar.typescript.lcov.reportPaths=coverage/lcov.info
        sonar.coverage.exclusions=test/**,*.test.ts,**/*.test.ts,*.spec.ts,*.data.ts,__tests__/**
        sonar.branch.name=$(Build.SourceBranchName)

  - task: Npm@1
    displayName: "Install dependencies in Project"
    inputs:
      command: custom
      workingDir: "$(System.DefaultWorkingDirectory)"
      verbose: false
      customCommand: run installDependenciesInProject

  - task: Npm@1
    displayName: "Install dependencies by Task"
    inputs:
      command: custom
      workingDir: "$(System.DefaultWorkingDirectory)"
      verbose: false
      customCommand: run installDependenciesByTask

  - task: Npm@1
    displayName: "Build by Task"
    inputs:
      command: custom
      workingDir: "$(System.DefaultWorkingDirectory)"
      verbose: false
      customCommand: run buildByTask

  - task: Npm@1
    displayName: "Unit Test"
    inputs:
      command: custom
      workingDir: "$(System.DefaultWorkingDirectory)"
      verbose: false
      customCommand: run test

  - task: SonarSource.sonarqube.6D01813A-9589-4B15-8491-8164AEB38055.SonarQubeAnalyze@4
    displayName: "Run Code Analysis"

  - task: sonar-buildbreaker@8
    inputs:
      SonarQube: "SonarQube"

  - task: Npm@1
    displayName: "Install only production dependencies by Task"
    inputs:
      command: custom
      workingDir: "$(System.DefaultWorkingDirectory)"
      verbose: false
      customCommand: run installOnlyProductionDependenciesByTask
